config/routes.rb
FLP::Application.routes.draw do

  root 'visitor#index', as: 'visitor'
  get '/admin' => 'visitor#admin_login'
  post '/admin' => 'visitor#admin_logout'
  post '/visitor/check_admin_login' => 'visitor#check_admin_login'
  get '/users/balances' => 'users#balances'
  put '/users/balances' => 'users#update_user_balance'

 namespace :visitor do

    get 'index' => :index
    get 'register' => :register
    get 'about' => :about
    get 'contact' => :contact
    get 'pools' => :pools
    get 'rules' => :rules
    get 'privacy' => :privacy
    get 'register_confirmation' => :register_confirmation
    get 'update_confirmation' => :update_confirmation
 end

  get "visitor/logout"
  post "visitor/login"
  post "visitor/create_password_reset_token", to: 'visitor#create_password_reset_token'
  post "visitor/update_password", to: 'visitor#save_password_update'
  get "visitor/password_reset"
  get "visitor/password_update", to: 'visitor#password_update'
  get "visitor/overview", to: 'visitor#overview'
  get "dashboard/contests"

  get "dashboard/my_pools", to: 'dashboard#my_pools'
  get "dashboard/my_pools/:id", to: 'dashboard#my_pools'

  get "dashboard/my_pools/ticket/:id", to: 'dashboard#update_selected_tickets'

  get "dashboard/my_tickets"

  get "dashboard/my_pools/picks/round/:id", to: 'dashboard#current_round'

  get "dashboard/overview", to: 'dashboard#overview'
  get "dashboard/overview/:id", to: 'dashboard#overview'
  get "dashboard/overview/pool/:id", to: 'dashboard#overview'
  get "dashboard/overview/round/:id", to: 'dashboard#overview'
  get "dashboard/schedule", to: 'dashboard#schedule'
  get "dashboard/schedule/:id", to: 'dashboard#schedule'
  post "dashboard/register_ticket" , to: 'dashboard#register_ticket_to_pool'
  get "dashboard/ticket_confirmation", to: 'dashboard#ticket_confirmation'
  get "dashboard/stat_recap", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/pool/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/round/:id", to: 'dashboard#stat_recap'
  get "dashboard/upcoming_pools"
  get "dashboard/current_pools"
  post "dashboard/save_pick", to: 'dashboard#save_pick'

  resources :games

  resources :tickets do
    put :disable, on: :member
  end

  resources :picks

  resources :leagues

  resources :sports

  resources :teams

  resources :users do
    get :manage, on: :member
    put :update_managed_pick, on: :member
    post :add_managed_pick, on: :member
  end

  post "rounds/new", to: 'rounds#new'

  resources :rounds do
    get :history, on: :member
    put :complete, on: :member
    post :display_stat, on: :member
  end

  resources :pools do
    get :manage, on: :member
    get :stat_recap, on: :member
    post :display_stat, on: :member
  end

end

app/models/pool.rb
# == Schema Information
#
# Table name: pools
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  prize            :integer
#  cost             :integer
#  number_of_rounds :integer
#  start_date       :datetime
#  deadline         :datetime
#  overview         :text
#  created_at       :datetime
#  updated_at       :datetime
#  league_id        :integer
#  end_date         :datetime
#  recap            :text
#

class Pool < ActiveRecord::Base
  validates :number_of_tickets, :number_of_rounds, :cost, :prize, :max_user_credit, presence: true
  validates :number_of_rounds, :max_user_credit,
            numericality: {greater_than_or_equal_to: 0}
  validates :number_of_tickets, :cost, :prize,
            numericality: {greater_than_or_equal_to: 1}
  
  has_many :rounds, dependent: :destroy
  has_many :tickets, dependent: :destroy
  belongs_to :league
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy, :manage, :stat_recap, :display_stat]
  layout "backend"



  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all
    session[:pool_id] = nil

    # Send a JS representation of the Pool index in case of an AJAX call (partial)
    # or a complete HTML page otherwise (show action for now)
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /pools/1/manage
  def manage
    @pool = Pool.find_by(id: session[:pool_id])
  end

  def stat_recap

  end

  def display_stat
    success_notice_message =
        @pool.display_stat ? 'Stats are now hidden from users in dashboard' :
            'Stats are now published to users in dashboard'
    error_notice_message =
        @pool.display_stat ? 'Could not hide stats from users in dashboard' :
            'Could not publish stats to users on in dashboard'
    @pool.display_stat = !@pool.display_stat

    if @pool.save
      respond_to do |format|
        format.html {redirect_to manage_pool_path(@pool),
                                 flash:{notice: success_notice_message,
                                        success: true}}
      end
    else
      respond_to do |format|
        format.html {redirect_to manage_pool_path(@pool),
                                 flash:{notice: error_notice_message,
                                        success: true}}
      end
    end

  end

  # GET /pools/1
  # GET /pools/1.json
  def show
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
  end

  # POST /pools
  # POST /pools.json
  def create

    @pool = Pool.new

    @pool.name = params[:pool][:name]
    @pool.league_id = params[:pool][:league_id].to_i
    @pool.cost = params[:pool][:cost].to_i
    @pool.prize = params[:pool][:prize].to_i
    @pool.number_of_tickets = params[:pool][:number_of_tickets].to_i
    @pool.max_user_credit = params[:pool][:max_user_credit].to_i
    number_of_rounds =  params[:pool][:number_of_rounds].to_i
    @pool.number_of_rounds = number_of_rounds
    @pool.start_date = datetime_from_params_hash(params[:pool], :start_date)
    @pool.end_date = datetime_from_params_hash(params[:pool], :end_date)
    @pool.deadline = datetime_from_params_hash(params[:pool], :deadline)
    @pool.overview = params[:pool][:overview]



    respond_to do |format|
      if @pool.save

        if number_of_rounds > 0
          # Create a default empty qualification round
          qualifications =  Round.new
          qualifications.with_games = false
          qualifications.pool = @pool
          qualifications.start_date = @pool.start_date + 2.days
          qualifications.end_date = @pool.start_date + 5.days
          qualifications.deadline = @pool.start_date + 1.day
          qualifications.save
          qualification_history  = RoundHistory.new
          qualification_history.round = qualifications
          qualification_history.save

          # Plus a number of dual-game rounds corresponding to the pool number_of_rounds - 1
          (number_of_rounds-1).times do |index|
            round = Round.new
            round.with_games = true
            round.pool = @pool
            round.start_date = @pool.start_date + (8*index).days
            round.end_date = @pool.start_date + (13*index).days
            round.deadline = @pool.start_date + (7*index).days
            round.save
            round_history = RoundHistory.new
            round_history.round = round
            round_history.save
          end
        end

        format.html { redirect_to pools_path,flash:
            {notice: 'Pool was successfully created.' ,success: true}}
        format.json { render action: 'show', status: :created, location: @pool }
      else
        format.html { render action: 'new', flash:
            {notice: 'Could not add pool.' ,success: false}}
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update

    if params[:commit] == "Save Report"
      @pool.recap = params[:pool][:recap]
    else
      @pool.name = params[:pool][:name]
      @pool.league_id = params[:pool][:league_id].to_i
      @pool.cost = params[:pool][:cost].to_i
      @pool.prize = params[:pool][:prize].to_i
      @pool.number_of_tickets = params[:pool][:number_of_tickets].to_i
      @pool.max_user_credit = params[:pool][:max_user_credit].to_i
      @pool.start_date = datetime_from_params_hash(params[:pool], :start_date)
      @pool.end_date = datetime_from_params_hash(params[:pool], :end_date)
      @pool.deadline = datetime_from_params_hash(params[:pool], :deadline)
      @pool.overview = params[:pool][:overview]
    end

    respond_to do |format|
      if @pool.save
        format.html { redirect_to pools_path,flash:
            {notice: 'Pool successfully updated.' ,success: true} }
        format.json { head :no_content }
      else
        format.html { render action: 'edit', flash:
            {notice: 'There was a problem updating the pool.  It could not updated' ,success: false} }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
      session[:pool_id] = @pool.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pool_params
      params.require(:pool).permit(:name, :prize, :cost, :number_of_rounds, :start_date, :deadline, :overview)
    end
    # Helper method that parses a datetime string hash elements and returns a datetime object
    def datetime_from_params_hash(hash, date_symbol)

      symbol_string = date_symbol.to_s

      DateTime.new(hash[symbol_string + '(1i)'].to_i,
                   hash[symbol_string + '(2i)'].to_i,
                   hash[symbol_string + '(3i)'].to_i,
                   hash[symbol_string + '(4i)'].to_i,
                   hash[symbol_string + '(5i)'].to_i)
    end


end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= bootstrap_form_for @pool, layout: :inline do |f| %>

    <table class="table table-striped" style="width: 100%;">
      <tbody>
          <tr>
            <td colspan="3">
            League
            <%= f.collection_select :league_id,
                                    League.all,
                                    :id,
                                    :name,
                                    {hide_label: true}%>
          </td>
          </tr>
        <tr>
          <td>
            Name
            <%= f.text_field :name, hide_label: true %>
          </td>
          <td>
            Number of Tickets
            <%= f.number_field :number_of_tickets, hide_label: true %>
          </td>
          <td>
            Max User Credit
            <%= f.number_field :max_user_credit, hide_label: true %>
          </td>
        </tr>
        <tr>
          <td>
            Prize
            <%= f.number_field :prize, hide_label: true %>
          </td>
          <td>
            Cost
            <%= f.number_field :cost, hide_label: true %>
          </td>
          <% if @pool.new_record?%>
              <td>
                Number of Rounds
                <%= f.number_field :number_of_rounds, hide_label: true %>
              </td>
          <% else %>
              <td>
                Number of Rounds
                <p style="font-weight: bold; font-size: large"><%= @pool.rounds
                                                               .count %></p>
              </td>
          <% end %>
        </tr>
        <tr>
          <td>
            Start Date
            <%= f.date_select :start_date, hide_label: true %>
          </td>
          <td>
            End Date
            <%= f.date_select :end_date, hide_label: true %>
          </td>
          <td>
            Deadline
            <%= f.date_select :deadline, hide_label: true %>
          </td>
        </tr>
      </tbody>
    </table>

    <h2>Overview</h2>

    <table style="width: 100%">
      <tbody>
      <tr>
        <td>
          <%= f.text_area :overview, class: 'tinymce', hide_label: true, :rows => 40, :cols => 120 %>
        </td>
      </tr>
      </tbody>
    </table>

<br>
    <div class="actions">
    <span><%= f.submit 'Save Pool', class: "btn btn-danger"%></span>
  </div>

<br>



    <%= tinymce %>

<% end %>

app/views/pools/_pool.html.erb
<!-- @brief Partial file for rendering pool model representation by jQuerry as
            as a response to an AJAX call (example: Pools link in the sidebar) or other views/layouts
     @param past_pool is local variable passed to the partial explicitly. When set to true,
            it means partial is to be styled as a past pool before being rendered
     @author Mehdi Mahmoudi
-->

<% if past_pool %>
    <tr>
      <td><%= pool.name %></td>
      <td><%= pool.prize %></td>
      <td><%= pool.cost %></td>
      <td><%= pool.rounds.count %></td>
      <td><%= pool.start_date %></td>
      <td><%= pool.deadline %></td>
      <td >
        <span class="glyphicon glyphicon-open pool-action-browse">
          Browse
        </span>
      </td>
    </tr>
<% else %>
    <tr>
      <td><%= pool.name %></td>
      <td><%= pool.prize %></td>
      <td><%= pool.cost %></td>
      <td><%= pool.rounds.count %></td>
      <td><%= pool.start_date %></td>
      <td><%= pool.deadline %></td>
      <td style="text-align: right" data-no-turbolink="true">
        <%= link_to 'Manage', manage_pool_path(pool)%>
        <span class="glyphicon glyphicon-dashboard pool-action-manage">
        </span>
        <br>
        <%= link_to 'Edit', edit_pool_path(pool)%>
        <span class="glyphicon glyphicon-pencil pool-action-edit">
        </span>
        <br>
        <%= link_to 'S&Rs', stat_recap_pool_path(pool)%>
        <span class="glyphicon glyphicon-stats pool-action-manage">
        </span>
        <br>
        <%= link_to 'Remove', pool_path(pool), method: :delete,
                    data:{confirm: "Are you sure you want to delete pool:  #{pool.name}?
This will also remove all rounds (#{pool.rounds.count} round(s)) and tickets (#{pool.tickets.count} ticket(s)) associated with this pool"} %>
        <span class="glyphicon glyphicon-trash pool-action-manage">
        </span>
      </td>
    </tr>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing pool</h1>

<%= render 'form' %>

app/views/pools/index.html.erb
<h1>Pools Overview</h1>

<!-- Current Pools-->

<h2 id="active-pools-label">Active Pools</h2>

<% if @pools.where("DATE(?) BETWEEN start_date AND end_date", Date.today).empty? %>
    <div class="alert alert-info">No pools to display</div>
<% else %>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Prize</th>
        <th>Cost</th>
        <th>Number of rounds</th>
        <th>Start date</th>
        <th>Deadline</th>
        <th>Action</th>
      </tr>
      </thead>

      <tbody>
        <%= render @pools.where("DATE(?) BETWEEN start_date AND end_date", Date.today),
                   past_pool: false %>
      </tbody>
    </table>
<% end %>



<!-- Planned Pools -->

<h2 id="upcoming-pools-label">Upcoming Pools</h2>

<% if @pools.where("start_date > ?", Date.today).empty? %>
    <div class="alert alert-info">No pools to display</div>
<% else %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Prize</th>
        <th>Cost</th>
        <th>Number of rounds</th>
        <th>Start date</th>
        <th>Deadline</th>
        <th>Action</th>
      </tr>
      </thead>

      <tbody>
        <%= render @pools.where("start_date > ?", Date.today), past_pool: false %>
      </tbody>
    </table>
<% end %>

<!-- Past Pools -->
<h2 id="past-pools-label">Past Pools</h2>

<% if @pools.where("end_date < ?", Date.today).empty? %>
    <div class="alert alert-info">No pools to display</div>
<% else %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Prize</th>
        <th>Cost</th>
        <th>Number of rounds</th>
        <th>Start date</th>
        <th>Deadline</th>
        <th>Action</th>
      </tr>
      </thead>

      <tbody>
        <%= render @pools.where("end_date < ?", Date.today), past_pool: true %>
      </tbody>
    </table>
<% end %>



<br>


<%= button_to 'Create Pool', new_pool_url, class:"btn btn-primary", type:"button", method: :get %>

<br>

app/views/pools/index.js.erb
/**
 * @brief Allows to process server sent HTML fragment in the browser's JS DOM environment
 */

// Fetch pools from server through the partial block and render them to the main content area
//$('#main').html(<table class="table table-striped"> <tbody>).append("<%= escape_javascript render(@pools) %>").append(</tbody> </table>);
$('#main').html("<%= escape_javascript render(@pools) %>");

app/views/pools/manage.html.erb
<h1><%= @pool.name %></h1>

<h2 id="remaining-tickets-label">Remaining Tickets</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Ticket Value</th>
    <th>Ticket #</th>
    <th>Date of Sale</th>
    <th>Validity</th>
  </tr>
  </thead>

  <tbody>
  <% @pool.tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.user.username %></td>
        <td><%= ticket.user.email %></td>
        <td><%= ticket.value %></td>
        <td><%= ticket.user.tickets.index(ticket) + 1%></td>
        <td><%= ticket.date_of_sale %></td>
        <td><%= ticket.validity ? 'Valid' : 'Expired' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div style="float: right">
  <%= button_to (@pool.display_stat ? 'Hide Stats' : 'Display Stats'),
                display_stat_pool_path(@pool), class: (@pool.display_stat ? "btn btn-info" : "btn btn-success") %>
</div>

<h2 id="rounds-label">Rounds</h2>
<table class="table round-panel">
  <tbody>
  <% @pool.rounds.order(:with_games, :start_date).each do |round| %>
  <tr>
    <td>
      <%= render round, render_history: false %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

<span class="pool-action-add-round">
  <%= link_to 'Add Rounds to Pool',
                new_round_path(with_games: true),
                class:"btn btn-danger",
                type:"button"%>
</span>

<span class="pool-action-add-round">
  <%= link_to 'Add Qualifications to Pool',
              new_round_path(with_games: false),
              class:"btn btn-info",
              type:"button"%>
</span>

app/views/pools/new.html.erb
<h1>New pool</h1>

<%= render 'form' %>

app/views/pools/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @pool.name %>
</p>

<p>
  <strong>Prize:</strong>
  <%= @pool.prize %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @pool.cost %>
</p>

<p>
  <strong>Number of rounds:</strong>
  <%= @pool.number_of_rounds %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @pool.start_date %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @pool.deadline %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @pool.overview %>
</p>

<%= link_to 'Edit', edit_pool_path(@pool) %> |
<%= link_to 'Back', pools_path %>

app/views/pools/stat_recap.html.erb
<%= bootstrap_form_for @pool, layout: :inline do |f| %>

    <h1>Stats and Recaps</h1>

    <h2>Pool Statistics</h2>

    <h2>Recap</h2>

    <%= f.text_area :recap, class: 'tinymce', :rows => 40, :cols => 120, hide_label: true %>

    <div class="actions" style="margin-top: 2%">
      <span><%= f.submit 'Save Report', class: "btn btn-danger"%></span>
    </div>

    <br>

    <%= tinymce %>
<% end %>