config/routes.rb
FLP::Application.routes.draw do

  root 'visitor#index', as: 'visitor'
  get '/admin' => 'visitor#admin_login'
  post '/admin' => 'visitor#admin_logout'
  post '/visitor/check_admin_login' => 'visitor#check_admin_login'
  get '/users/balances' => 'users#balances'
  put '/users/balances' => 'users#update_user_balance'

 namespace :visitor do

    get 'index' => :index
    get 'register' => :register
    get 'about' => :about
    get 'contact' => :contact
    get 'pools' => :pools
    get 'rules' => :rules
    get 'privacy' => :privacy
    get 'register_confirmation' => :register_confirmation
    get 'update_confirmation' => :update_confirmation
 end

  get "visitor/logout"
  post "visitor/login"
  post "visitor/create_password_reset_token", to: 'visitor#create_password_reset_token'
  post "visitor/update_password", to: 'visitor#save_password_update'
  get "visitor/password_reset"
  get "visitor/password_update", to: 'visitor#password_update'
  get "visitor/overview", to: 'visitor#overview'
  get "dashboard/contests"

  get "dashboard/my_pools", to: 'dashboard#my_pools'
  get "dashboard/my_pools/:id", to: 'dashboard#my_pools'

  get "dashboard/my_pools/ticket/:id", to: 'dashboard#update_selected_tickets'

  get "dashboard/my_tickets"

  get "dashboard/my_pools/picks/round/:id", to: 'dashboard#current_round'

  get "dashboard/overview", to: 'dashboard#overview'
  get "dashboard/overview/:id", to: 'dashboard#overview'
  get "dashboard/overview/pool/:id", to: 'dashboard#overview'
  get "dashboard/overview/round/:id", to: 'dashboard#overview'
  get "dashboard/schedule", to: 'dashboard#schedule'
  get "dashboard/schedule/:id", to: 'dashboard#schedule'
  post "dashboard/register_ticket" , to: 'dashboard#register_ticket_to_pool'
  get "dashboard/ticket_confirmation", to: 'dashboard#ticket_confirmation'
  get "dashboard/stat_recap", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/pool/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/round/:id", to: 'dashboard#stat_recap'
  get "dashboard/upcoming_pools"
  get "dashboard/current_pools"
  post "dashboard/save_pick", to: 'dashboard#save_pick'

  resources :games

  resources :tickets do
    put :disable, on: :member
  end

  resources :picks

  resources :leagues

  resources :sports

  resources :teams

  resources :users do
    get :manage, on: :member
    put :update_managed_pick, on: :member
    post :add_managed_pick, on: :member
  end

  post "rounds/new", to: 'rounds#new'

  resources :rounds do
    get :history, on: :member
    put :complete, on: :member
    post :display_stat, on: :member
  end

  resources :pools do
    get :manage, on: :member
    get :stat_recap, on: :member
    post :display_stat, on: :member
  end

end

app/controllers/dashboard_controller.rb
# Instance variables: @pools, @my_pools, @my_tickets, @my_tickets_collection,
# @selected_pool, @selected_ticket

class DashboardController < ApplicationController
  skip_before_action :authorize
  before_action :set_pool, only: [:overview, :register_ticket_to_pool, :ticket_confirmation, :my_pools]
  before_filter :current_user
  before_filter :version_details
  before_action :all_tickets, only: [:my_pools, :update_selected_tickets, :overview, :stat_recap]
  before_action :contests, only: [:overview, :stat_recap, :schedule]
  #before_action :my_pools, only: [:overview, :schedule, :stat_recap]

  layout "dashboard"

  def contests
   @pools = Pool.all
  end


  # Gets all tickets for user. Used to retrieve pools in which she is registered through tickets.
  # Request isn't asking for a particular pool, i.e., /my_pools or this is the first time my_pools
  # is requested
  def all_tickets
    @my_tickets_collection = @current_user.tickets.order(:expiry_date)

    # Mark expired tickets as invalid if they haven't paid before deadline
    # Note: The all_tickets function needs to be called at least once for the ticket to be invalidated. Hence, it should
    # be invoked before any function involving tickets in the dashboard
    @my_tickets = {}
    @my_tickets_collection.each_with_index do |ticket, index|
      @my_tickets[index+1] = ticket


      # Disable ticket eliminitation when pool is past deadline for FIFA WorldCup
=begin
      if (ticket.expiry_date == ticket.pool.deadline) && (ticket.validity) && (DateTime.current >= ticket.pool.deadline)
        ticket.validity = false
        # Save and notify user that her ticket was eliminated the first time she logs in to the dashboard
        # Note: This is a temporary solution until task scheduling is implemented
        if ticket.save
          UserNotifier.eliminated(ticket).deliver
        end
      end
=end
    end

  end

  # Gets tickets implicitly from the selected pool. @selected_pool is assumed to be valid
  # Selected pool is already set, which means coming from a /my_pools/id request
  def update_selected_tickets

    # Set active ticket instance variable for rendering
    if session[:selected_ticket]
      @active_ticket = Ticket.find_by(id: session[:selected_ticket])
    else
      if @my_tickets.empty?
        @my_pools = nil
      else
        @active_ticket = @my_tickets_collection.first
        session[:selected_ticket] = @active_ticket.id
      end
    end

    tickets_collection_for_pool =
        @current_user.tickets.where(pool_id: session[:selected_pool]).order(:expiry_date)

    @my_tickets = {}
    tickets_collection_for_pool.each_with_index do |ticket, index|
      @my_tickets[index+1] = ticket
    end

    # Get the selected ticket from URL or assign first ticket as default ticket for pool
    if request.fullpath.include?('/ticket/')

      # Look for the selected ticket in there
      selected_ticket_index ||= params[:id].to_i
      if params[:id]
        session[:selected_ticket] =  @my_tickets[selected_ticket_index].id
        session[:selected_ticket_index] = selected_ticket_index
      else
        session[:selected_ticket] = @my_tickets[1].id
        session[:selected_ticket_index] = 0
      end

      respond_to do |format|
        format.html { redirect_to controller: :dashboard,
                                  action: :my_pools,
                                  id: session[:selected_pool_index] }
      end

    end



  end

  def my_pools

    @browser = Browser.new(:ua => request.user_agent)

    # Instance container for user pools
    @my_pools = []

    if @my_tickets.empty?
      @my_pools = nil
    else

      # Retrieve pools from user tickets
      @my_tickets_collection.each do |ticket|
        unless @my_pools.include?(ticket.pool)
          @my_pools << ticket.pool
        end
      end

      # Sort pools, if any, by id
      @my_pools.sort_by {|o| o[:id]} unless @my_pools.empty?

      # Get the selected pool from URL or assign first pool as default pool
      # When my_pools is triggered by a pools drop-down list select change or round change
      if (!request.fullpath.include?('/ticket/')) && (!request.fullpath.include?('/round/'))
        selected_pool_index ||= params[:id].to_i
        if params[:id]
          # Check if pool is different from current pool, if so reset the current round index
          # so that it can be set properly to the first round in the pool
          if session[:selected_pool] != @my_pools.at(selected_pool_index).id
            if session[:selected_pool] == nil
              session[:selected_pool] = @my_pools.first.id
            end
            session[:current_round] = nil
          end
          session[:selected_pool] = @my_pools.at(selected_pool_index).id
          session[:selected_pool_index] = selected_pool_index
        else
          # If a pool is already selected, example coming from ticket confirmation page
          if session[:selected_pool]
            # Retrieve its index from the my_pools collection (user exploring her pools) or set the selector
            # to the first user pool in the drop-down (user was exploring other pools that are not in my pools)
            if @my_pools.include?(Pool.find(session[:selected_pool]))
              session[:selected_pool_index] =  @my_pools.index(session[:selected_pool])
            else
              session[:selected_pool_index] = 0
              session[:selected_pool] = @my_pools.first.id
            end


          # Otherwise select fist pool in my pools list
          else
            session[:selected_pool] = @my_pools.first.id
            session[:selected_pool_index] = 0
          end

        end

        @active_pool = Pool.find_by(id: session[:selected_pool])

        # Update ticket collection to be displayed for the selected pool
        update_selected_tickets

        current_round unless session[:change_round]
      end


      # When this block is reached, my_pools was requested by either a regular my_pools request
      # or after a redirection upon updating current round by the current_round method
      # In both cases, any processing on the @current_round instnace mus be done after this block
      if (session[:current_round] != nil) && (session[:change_round] == true)
        @current_round = Round.find_by(id: session[:current_round])
        session[:change_round] = false
      elsif session[:current_round].nil?
        if Pool.find_by(id: session[:selected_pool]).rounds.empty?
          @current_round = nil
          return
        else
          first_round_id = Pool.find_by(id: session[:selected_pool]).rounds.first.id
          @current_round = Round.find_by(id: first_round_id)
        end
      elsif !session[:change_round]
        @current_round = Round.find_by(id: session[:current_round])
        puts @current_round.id
      end

      update_possible_picks

    end

  end

  def current_round
    @active_pool ||= Pool.find_by(id: session[:selected_pool])
    @current_round = nil

    # Request coming from clicking round div in pool view
    if request.fullpath.include?('/round/')
      unless @active_pool.rounds.empty?
        @current_round = @active_pool.rounds.order(:start_date).at(params[:id].to_i)
        session[:current_round] = @current_round.id
        session[:current_round_index] = params[:id]
        session[:change_round] = true
        if params[:current_view] == "schedule"
          respond_to do |format|
            format.html { redirect_to controller: :dashboard,
                                      action: :schedule,
                                      id: session[:selected_pool_index] }
          end
        else
          respond_to do |format|
            format.html { redirect_to controller: :dashboard,
                                      action: :my_pools,
                                      id: session[:selected_pool_index] }
          end
        end
      end



    # Called by my_pools to update current round
    else
      if @active_pool.rounds.blank?
        @current_round = nil
      else
        if session[:current_round].nil?
          @current_round = @active_pool.rounds.order(:start_date).first
          session[:current_round] = @current_round.id
        else
          @current_round = Round.find_by(id: session[:current_round])
        end

      end
    end

  end

  def upcoming_pools
    @pools= Pool.all
    @future_pools= @pools.where("start_date > ?", Date.today)
  end
  def current_pools
    @pools= Pool.all
    @current_pools= @pools.where("start_date < ? AND end_date > ? ", Date.today , Date.today)
  end

  def overview
    @browser = @browser = Browser.new(:ua => request.user_agent)
    session[:current_view] = "overview"

    if request.fullpath.include?('/pool/')
       # Get a pool from the pools collection by its id (equivalent to index since elements are sorted by index in .all)
       selection_index = params[:id].to_i
       @active_pool = @pools.at(selection_index)
       session[:selected_pool] = @active_pool.id
    else
       if params[:upcoming_pool]
         @active_pool = Pool.find_by(id: params[:upcoming_pool].to_i)
         session[:selected_pool] = @active_pool.id
       else
         if session[:selected_pool]
           @active_pool = Pool.find(session[:selected_pool])
         else
           @active_pool = @pools.at(0)
           session[:selected_pool] = @active_pool.id
         end
       end

    end
  end

  def schedule
    session[:current_view] = "schedule"

    @my_pools = Pool.all

    if params[:id]
      session[:selected_pool] = @my_pools.at(params[:id].to_i).id
      @active_pool = @my_pools.at(params[:id].to_i)
    end

    # If a pool is already selected, exemple coming from ticket confirmation page
    if session[:selected_pool]
      # Retrieve its index from the my_pools collection (user exploring her pools) or set the selector

app/helpers/dashboard_helper.rb
module DashboardHelper

  def has_tickets_without_picks(pool)
    ticket_without_picks = false
    pool.tickets.each do |ticket|
      pool.rounds.each do |round|
        unless ticket.picks.where(round: round).any?
          ticket_without_picks = true
          break
        end
      end
    end
    return ticket_without_picks
  end
end

app/views/dashboard/contests.html.erb
<h1>Pools</h1>
<table id="tableOfPools" width="85%" style="text-align: center; margin: 0 auto;">
  <thead>
  <tr>
    <th style="width: 55%" colspan="2"> Contest</th>
    <th style="width: 10%"> Prize</th>
    <th style="width: 10%"> Cost</th>
    <th style="width: 30%"> Starts on</th>
  </tr>
  </thead>
  <tbody id="">
 <% @pools.each do |pool| %>

      <% if pool.league.sport.name == "Football"%>
          <tr>
            <td><%= image_tag("frontend/FootAM1.png") %></td>
            <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id) %></td>
            <td>$<%= pool.prize %></td>
            <td>$<%= pool.cost %></td>
            <td><%= pool.start_date %></td>
          </tr>
      <% elsif pool.league.sport.name == "Hockey"%>
          <tr>
            <td><%= image_tag("frontend/Hockey1.png") %></td>
            <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id) %></td>
            <td>$<%= pool.prize %></td>
            <td>$<%= pool.cost %></td>
            <td><%= pool.start_date %></td>
          </tr>
      <% elsif pool.league.sport.name == "Basketball"%>
          <tr>
            <td><%= image_tag("frontend/Basket1.png") %></td>
            <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id) %></td>
            <td>$<%= pool.prize %></td>
            <td>$<%= pool.cost %></td>
            <td><%= pool.start_date %></td>
          </tr>
      <% elsif pool.league.sport.name == "Soccer"%>
          <tr>
            <td><%= image_tag("frontend/FootBall1.png") %></td>
            <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id) %></td>
            <td>$<%= pool.prize %></td>
            <td>$<%= pool.cost %></td>
            <td><%= pool.start_date %></td>
          </tr>
      <%end%>

  <% end %>
  </tbody>


</table>

app/views/dashboard/current_pools.html.erb
<h1>Current Pools</h1>

<% if @current_pools.any?%>
    <table id="tableOfPools" width="100%" style="text-align: center;">
      <thead>
      <tr>
        <th style="width: 67%" colspan="2"> Contest</th>
        <th style="width: 10%"> Prize</th>
        <th style="width: 10%"> Cost</th>
        <th style="width: 20%"> Starts on</th>
      </tr>
      </thead>
      <tbody id="">
      <% @current_pools.each do |pool| %>

          <% if pool.league.sport.name == "Football"%>
              <tr>
                <td><%= image_tag("frontend/FootAM1.png") %></td>
                <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id)%></td>
                <td><%= pool.prize %></td>
                <td><%= pool.cost %></td>
                <td><%= pool.start_date %></td>
              </tr>
          <% elsif pool.league.sport.name == "Hockey"%>
              <tr>
                <td><%= image_tag("frontend/Hockey1.png") %></td>
                <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id)%></td>
                <td><%= pool.prize %></td>
                <td><%= pool.cost %></td>
                <td><%= pool.start_date %></td>
              </tr>
          <% elsif pool.league.sport.name == "Basketball"%>
              <tr>
                <td><%= image_tag("frontend/Basket1.png") %></td>
                <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id)%></td>
                <td><%= pool.prize %></td>
                <td><%= pool.cost %></td>
                <td><%= pool.start_date %></td>
              </tr>
          <% elsif pool.league.sport.name == "Soccer" %>
              <tr>
                <td><%= image_tag("frontend/FootBall1.png") %></td>
                <td><%= link_to pool.name, dashboard_overview_path(upcoming_pool: pool.id)%></td>
                <td><%= pool.prize %></td>
                <td><%= pool.cost %></td>
                <td><%= pool.start_date %></td>
              </tr>
          <%end%>

      <% end %>
      </tbody>
    </table>
<% else %>
    <div id="scheduleWeek" style="height: 10%; width: 70%; margin-top: 20%;
            margin-left: auto; margin-right: auto; text-align: center; padding: 2%;">
      There are no pools currently being played
    </div>
<% end %>

app/views/dashboard/my_tickets.html.erb
<h1><%= @current_user.first_name %> <%= @current_user.last_name %></h1>
<h4 style="color: dodgerblue; margin-left: 2em"><%= link_to "Edit #{@current_user.username}", visitor_register_path(:render_edit => true) %></h4>
<br>
<h2 style="text-align: center;">Account Summary</h2>

<ul style="font-size: larger">
  <li style="font-weight: bold; margin-bottom: 2em;">Your current balance: $<%= @current_user.balance %></li>
  <li>Last deposit: $<%= @current_user.last_deposit%></li>
  <li>Member since: <%= @current_user.created_at %></li>
  <li>Last login: <%= @current_user.last_login %></li>
</ul>


  <h2 style="text-align: center;margin-top: 4%;">Tickets</h2>
  <div style="width: 100% ;padding-top: 1%; height: 650px;"  class="ticketsDiv">
    <table class="tableTickets"   width="95%"  style="text-align: center; margin: 0 auto;">

      <thead>
      <tr>
        <th>
          Tickets
        </th>
        <th style="width: 30%">
          Pools Name
        </th>
        <th style="width: 20%">
          Pools Deadline
        </th>
        <th style="width: 20%">
          Purchase Date
        </th>
        <th style="width: 10%">
          Validity
        </th>
        <th style="width: 10%">
          Value
        </th>
      </tr>
      </thead>
      <tbody id="DetailsOfAliveTickets">
        <% @current_user.tickets.each do |ticket| %>
          <tr>
            <td>TK<%= ticket.id %></td>
            <td><%= ticket.pool.name %></td>
            <td><%= ticket.pool.deadline %></td>
            <td><%= ticket.date_of_sale %></td>
            <td>
              <% if ticket.validity %>
                <span style="color: green">Valid</span>
              <% else %>
                  <span style="color: darkred">Expired</span>
              <% end %>
            </td>
            <td> $<%= ticket.value %></td>
          </tr>
        <%end%>
        <tr><td colspan='5' style='background-color: #ffffff;box-shadow: none;'>TOTAL</td> <td> $<%= total_ticket %></td></tr>
      </tbody>
    </table>
  </div>

app/views/dashboard/overview.html.erb
<h1>Overview</h1>

<% unless @pools.blank? %>

    <div class="contentpools" style="margin-top: 2%">
      <!--------Mypools dropdow select --------------->
      <div style="margin: 0 auto;">
        <label for="myPools">All pools</label>
        <%= select_tag "pools",
                       options_from_collection_for_select(@pools, :id, :name,
                                                          session[:selected_pool]),
                       onchange: 'handle_selection("pools", "overview", this)',
                       :id=>"myPools" %>
      </div>
      <!--------End mypools dropdown select --------------->
    </div>

<% end %>


<nav id="poolnav">
  <ul id="subMenuPool">

    <li><%= link_to 'Overview', dashboard_overview_path%></li>
    <li><%= link_to 'My Picks', dashboard_my_pools_path%></a></li>
    <li><%= link_to 'Schedule', dashboard_schedule_path%></li>
    <li class="last"><%= link_to 'Stats & Recap', dashboard_stat_recap_path %></li>
  </ul>
</nav>

<% if @active_pool %>

    <div style="margin-top: 10%; text-align: center">
      <% if (@current_user.balance < 0) && ((-@current_user.balance) >= @active_pool.max_user_credit) %>
          <div id="scheduleWeek" style="height: 10%; width: 70%; margin: 0 auto; text-align: center;">
            Sorry. You have exceeded your maximum allowed credit limit. Please contact us at
            <a style="color: #EF720C" href="mailto:info@fatladypools.com">info@fatladypools.com</a> for more details.
          </div>
      <% elsif @active_pool.tickets.count >= @active_pool.number_of_tickets%>
          <div id="scheduleWeek" style="height: 10%; width: 70%; margin: 0 auto; text-align: center;">
            This pool is soldout.
          </div>
      <% elsif @active_pool.deadline <= DateTime.current || @active_pool.start_date <= DateTime.current %>
          <div id="scheduleWeek" style="height: 10%; width: 70%; margin: 0 auto; text-align: center;">
            You are beyond deadline for registering to this pool. You can still follow pool schedule, stats and recap.
          </div>
      <% else %>
          <div style="text-align: center">
            <%= button_to 'Buy ticket', dashboard_register_ticket_path, class:"btn btn-danger", style:"height: 5em; width: 10em; font-size: 18px;",
                          data:{confirm: "Are you sure you want to buy this ticket? This will take $#{@active_pool.cost} from your balance."} %>
          </div>
      <% end %>

    </div>
<% end %>

<% if @browser.safari? || @browser.firefox? %>

    <div id="overviewArea">
      <% if @active_pool %>

          <%=raw @active_pool.overview %>

      <% end %>

    </div>

<% else %>
    <div id="overviewArea">
      <% if @active_pool %>

          <%=raw @active_pool.overview %>

      <% end %>

    </div>
<% end %>

app/views/dashboard/schedule.html.erb
<h1>Schedule</h1>

<% unless @my_pools.blank? %>

    <div class="contentpools" style="margin-top: 2%">
      <!--------Mypools dropdown select --------------->
      <div style="margin: 0 auto;">
        <label for="myPools">My pools</label>
        <%= select_tag "pools",
                       options_from_collection_for_select(@my_pools, :id, :name,
                                                          session[:selected_pool]),
                       onchange: 'handle_selection("pools", "schedule", this)',
                       :id=>"myPools" %>
      </div>
      <!--------End mypools dropdow select --------------->
    </div>

<% end %>

<nav id="poolnav">
  <ul id="subMenuPool">

    <li><%= link_to 'Overview', dashboard_overview_path%></li>
    <li><%= link_to 'My Picks', dashboard_my_pools_path%></a></li>
    <li><%= link_to 'Schedule', dashboard_schedule_path%></li>
    <li class="last"><%= link_to 'Stats & Recap', dashboard_stat_recap_path%></li>
  </ul>
</nav>

<div class="contentpools">
  <div id="scheduleWeek">
    For more details, follow the official
    <a href="http://fifa.com/worldcup/matches/index.html#" target="_blank" style="color: #f1592a">FIFA Schedule and Results page</a>
  </div>
</div>

<div class="contentpools" style="max-height: 400px;">

  <% if @my_pools.nil? %>
      <div id="scheduleWeek">
        You are not registered to any pools yet
      </div>
  <% else %>

      <div style="min-height: 100%;width: 99%;margin: 3% auto 4%;">


            <!-------- Round number and title ------->
            <% if @current_round.nil? %>
                <div id="scheduleWeek">
                  This pool has no rounds yet
                </div>
            <% else %>
                <div id="scheduleWeek">
                  <% if @active_pool.rounds.order(:start_date).last == @current_round %>
                      <% if @current_round.complete %>
                          <span style="font-weight: bold; text-decoration: underline;">Active Round Summary:</span> <%= @current_round.name %>
                      <% else %>
                          <span style="font-weight: bold; text-decoration: underline;">Active Round Schedule:</span> <%= @current_round.name %>
                      <% end %>
                  <% else %>
                      <% if @current_round.complete %>
                          Result Summary - <%= @current_round.name %>
                      <% else %>
                          Schedule - <%= @current_round.name %>
                      <% end %>
                  <% end %>


                </div>
                <!--------End Round number and title ------->

                <!-------- Games table  ------->
                <div style="max-height: 300px; overflow-y: auto;">
                  <table id="TabWeek">
                    <thead>
                    <% if @current_round.with_games %>
                        <tr class="border">
                          <td>
                            Team 1
                          </td>
                          <td>
                            Team 2
                          </td>
                          <td>
                            Result
                          </td>
                        </tr>
                        </thead>
                        <tbody id="matchesSchedule">
                        <% @current_round.games.each do |game| %>
                            <tr class='border'>
                              <td><%= Team.find_by(id: game.first_team_id).name %></td>
                              <td><%= Team.find_by(id: game.second_team_id).name %></td>
                              <td>
                                <% if @current_round.complete %>
                                    <%= game.first_team_score %> - <%= game.second_team_score %>
                                <% else %>
                                    N/A - N/A
                                <% end %>
                              </td>
                            </tr>
                        <% end %>
                        </tbody>
                        <tfoot style="background: grey;min-height: 2em;">
                        </tfoot>
                        </table>

                    <% else %>
                        <table style="width:100%; " id="TabWeek">
                          <thead>
                          <tr class="border">
                            <td>
                              Team
                            </td>
                            <td>
                              Outcome
                            </td>
                          </tr>
                          </thead>
                          <tbody id="matchesSchedule">
                          <% @current_round.games.each do |game| %>
                              <tr class='border'>
                                <td><%= Team.find_by(id: game.first_team_id).name %></td>
                                <td>
                                  <% if @current_round.complete %>
                                      <% if game.first_team_id == game.winner_id  %>
                                          Advances
                                      <% else %>
                                          Eliminated
                                      <% end %>
                                  <% else %>
                                      N/A
                                  <% end %>
                                </td>
                              </tr>
                          <% end %>
                          </tbody>
                          <tfoot style="background: grey;min-height: 2em;">
                          </tfoot>
                        </table>
                    <% end %>
                    </div>

                <!-------- End Games table  ------->
                </div>

                <div id="PoolsWeekBloc" style="width: 100%;">

                  <!-------- Rounds table table  ------->
                  <table id="PoolsWeek">
                    <tbody>
                    <tr>
                      <% @active_pool.rounds.order(:start_date).each_with_index do |round, index| %>
                          <% if @current_round == round %>
                              <td id="week_1" style="background: #f26522;">
                                <%= link_to "#{round.name}",
                                            controller: :dashboard,
                                            action: :current_round,
                                            id: index,
                                            current_view: "schedule",
                                            class: "myPoolsWeek" %>
                              </td>
                          <% else %>
                              <td id="week_1">
                                <%= link_to "#{round.name}",
                                            controller: :dashboard,
                                            action: :current_round,
                                            id: index,
                                            current_view: "schedule",
                                            class: "myPoolsWeek" %>
                              </td>
                          <% end %>

                      <% end %>
                    </tr>
                    </tbody>
                  </table>
                  <!-------- End Rounds table table  ------->

                  <% if @current_round.complete %>
                      <div id="scheduleWeek">
                        This round is closed.
                      </div>
                  <% end %>

            <% end %>




        </div>
  <% end %>


</div>

app/views/dashboard/ticket_confirmation.html.erb
<h2 style="color: green; text-align: center; margin-top: 10%"> Welcome to <%= @active_pool.name %>! </h2>

<br>
<br>

<p style="font-size:  1.5em; margin-top: 5%; margin-left: 10%;"> You are now registered in <%= @purchased_ticket.pool.name %>. </p>

<% if @purchased_ticket.expiry_date == @active_pool.deadline %>
    <p style="font-size:  1.5em; margin: 5%"> Your ticket expires on: <%= @purchased_ticket.expiry_date %> </p>
    <p style="font-size:  1.5em; margin: 5%"> Please proceed to payment by contacting us before this date.
      In the mean time you can start picking teams for the next rounds in this pool. Enjoy!
    </p>
    <br>
    <p style="font-size:  1.5em; font-weight: bold; text-align: center"> Your current balance is: <%= @current_user.balance %> </p>
<% else %>
    <br>
    <p style="font-size:  1.5em; font-weight: bold; text-align: center"> Your current balance is: <%= @current_user.balance %> </p>
<% end %>

    <p style="text-align: right; margin-right: 40%; margin-top: 10%;">
      <%= link_to 'Manage Picks', dashboard_my_pools_path, class: "btn btn-warning",
                  style: "text-decoration: none; font-size: 1.5em;" %>
    </p>

<br>
<br>

<div id="scheduleWeek" style="height: 10%; width: 70%; margin-top: 20%;
        margin-left: auto; margin-right: auto; text-align: center; padding: 2%;">
  Please make sure to check you Spam folder in your mail client. If you find the ticket confirmation e-mail there,
  you should whitelist it as a non-Spam mail.
</div>