config/routes.rb
FLP::Application.routes.draw do

  root 'visitor#index', as: 'visitor'
  get '/admin' => 'visitor#admin_login'
  post '/admin' => 'visitor#admin_logout'
  post '/visitor/check_admin_login' => 'visitor#check_admin_login'
  get '/users/balances' => 'users#balances'
  put '/users/balances' => 'users#update_user_balance'

 namespace :visitor do

    get 'index' => :index
    get 'register' => :register
    get 'about' => :about
    get 'contact' => :contact
    get 'pools' => :pools
    get 'rules' => :rules
    get 'privacy' => :privacy
    get 'register_confirmation' => :register_confirmation
    get 'update_confirmation' => :update_confirmation
 end

  get "visitor/logout"
  post "visitor/login"
  post "visitor/create_password_reset_token", to: 'visitor#create_password_reset_token'
  post "visitor/update_password", to: 'visitor#save_password_update'
  get "visitor/password_reset"
  get "visitor/password_update", to: 'visitor#password_update'
  get "visitor/overview", to: 'visitor#overview'
  get "dashboard/contests"

  get "dashboard/my_pools", to: 'dashboard#my_pools'
  get "dashboard/my_pools/:id", to: 'dashboard#my_pools'

  get "dashboard/my_pools/ticket/:id", to: 'dashboard#update_selected_tickets'

  get "dashboard/my_tickets"

  get "dashboard/my_pools/picks/round/:id", to: 'dashboard#current_round'

  get "dashboard/overview", to: 'dashboard#overview'
  get "dashboard/overview/:id", to: 'dashboard#overview'
  get "dashboard/overview/pool/:id", to: 'dashboard#overview'
  get "dashboard/overview/round/:id", to: 'dashboard#overview'
  get "dashboard/schedule", to: 'dashboard#schedule'
  get "dashboard/schedule/:id", to: 'dashboard#schedule'
  post "dashboard/register_ticket" , to: 'dashboard#register_ticket_to_pool'
  get "dashboard/ticket_confirmation", to: 'dashboard#ticket_confirmation'
  get "dashboard/stat_recap", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/pool/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/round/:id", to: 'dashboard#stat_recap'
  get "dashboard/upcoming_pools"
  get "dashboard/current_pools"
  post "dashboard/save_pick", to: 'dashboard#save_pick'

  resources :games

  resources :tickets do
    put :disable, on: :member
  end

  resources :picks

  resources :leagues

  resources :sports

  resources :teams

  resources :users do
    get :manage, on: :member
    put :update_managed_pick, on: :member
    post :add_managed_pick, on: :member
  end

  post "rounds/new", to: 'rounds#new'

  resources :rounds do
    get :history, on: :member
    put :complete, on: :member
    post :display_stat, on: :member
  end

  resources :pools do
    get :manage, on: :member
    get :stat_recap, on: :member
    post :display_stat, on: :member
  end

end

app/models/sport.rb
# == Schema Information
#
# Table name: sports
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Sport < ActiveRecord::Base
  has_many :leagues, dependent: :destroy
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]
  layout "backend"

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sport }
      else
        format.html { render action: 'new' }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:name)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1>Listing sports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.name %></td>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sport.name %>
</p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>