config/routes.rb
FLP::Application.routes.draw do

  root 'visitor#index', as: 'visitor'
  get '/admin' => 'visitor#admin_login'
  post '/admin' => 'visitor#admin_logout'
  post '/visitor/check_admin_login' => 'visitor#check_admin_login'
  get '/users/balances' => 'users#balances'
  put '/users/balances' => 'users#update_user_balance'

 namespace :visitor do

    get 'index' => :index
    get 'register' => :register
    get 'about' => :about
    get 'contact' => :contact
    get 'pools' => :pools
    get 'rules' => :rules
    get 'privacy' => :privacy
    get 'register_confirmation' => :register_confirmation
    get 'update_confirmation' => :update_confirmation
 end

  get "visitor/logout"
  post "visitor/login"
  post "visitor/create_password_reset_token", to: 'visitor#create_password_reset_token'
  post "visitor/update_password", to: 'visitor#save_password_update'
  get "visitor/password_reset"
  get "visitor/password_update", to: 'visitor#password_update'
  get "visitor/overview", to: 'visitor#overview'
  get "dashboard/contests"

  get "dashboard/my_pools", to: 'dashboard#my_pools'
  get "dashboard/my_pools/:id", to: 'dashboard#my_pools'

  get "dashboard/my_pools/ticket/:id", to: 'dashboard#update_selected_tickets'

  get "dashboard/my_tickets"

  get "dashboard/my_pools/picks/round/:id", to: 'dashboard#current_round'

  get "dashboard/overview", to: 'dashboard#overview'
  get "dashboard/overview/:id", to: 'dashboard#overview'
  get "dashboard/overview/pool/:id", to: 'dashboard#overview'
  get "dashboard/overview/round/:id", to: 'dashboard#overview'
  get "dashboard/schedule", to: 'dashboard#schedule'
  get "dashboard/schedule/:id", to: 'dashboard#schedule'
  post "dashboard/register_ticket" , to: 'dashboard#register_ticket_to_pool'
  get "dashboard/ticket_confirmation", to: 'dashboard#ticket_confirmation'
  get "dashboard/stat_recap", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/pool/:id", to: 'dashboard#stat_recap'
  get "dashboard/stat_recap/round/:id", to: 'dashboard#stat_recap'
  get "dashboard/upcoming_pools"
  get "dashboard/current_pools"
  post "dashboard/save_pick", to: 'dashboard#save_pick'

  resources :games

  resources :tickets do
    put :disable, on: :member
  end

  resources :picks

  resources :leagues

  resources :sports

  resources :teams

  resources :users do
    get :manage, on: :member
    put :update_managed_pick, on: :member
    post :add_managed_pick, on: :member
  end

  post "rounds/new", to: 'rounds#new'

  resources :rounds do
    get :history, on: :member
    put :complete, on: :member
    post :display_stat, on: :member
  end

  resources :pools do
    get :manage, on: :member
    get :stat_recap, on: :member
    post :display_stat, on: :member
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string(255)
#  password   :string(255)
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  phone      :string(255)
#  country    :string(255)
#  province   :string(255)
#  dob        :date
#  created_at :datetime
#  updated_at :datetime
#  balance    :integer
#

class User < ActiveRecord::Base

  validates :first_name, :last_name, :username, :email, :phone, :password, presence: true
  validates :password, format: {with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\Z/,
                                message: "password must be at least 6 characters long and include one number and one letter."}
  validates_confirmation_of :password
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
  validates :username, :email, uniqueness: true
  #validate :dob_must_yield_minimum_age

  has_many :tickets, dependent: :destroy
  has_many :pools, through: :tickets, uniq: true

  def compute_age
    (dob + 18.years) < Date.today
  end

  def dob_must_yield_minimum_age
    errors.add(:dob, "Date of birth is invalid. You have to be at least 18 years old.") unless compute_age
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :manage, :add_managed_pick, :update_managed_pick]
  layout "backend"

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def manage

  end

  def add_managed_pick

    # Parse information required for update
    team ||= Team.find(params[:team_id].to_i)
    ticket ||= Ticket.find(params[:ticket].to_i)
    round ||= Round.find(params[:round].to_i)

    # Do not update pick if drop down list selection hasn't changed
    unless ticket.picks.where(round_id: round.id).any?
        pick = Pick.new
        pick.ticket = ticket
        pick.team_id = team.id
        pick.round = round
        if pick.save
          # Notify user
          #UserNotifier.picked(@user, pick).deliver
          respond_to do |format|
            format.html {redirect_to manage_user_path(@user),
                                     flash: {notice: "Added pick #{team.name} for user #{@user.username} successfully",
                                             success: true}}
          end
        else
          respond_to do |format|
            format.html {redirect_to manage_user_path(@user),
                                     flash: {notice: "Could not add pick for user #{@user.username}",
                                             success: false}}
          end
        end
    end

  end

  def update_managed_pick

    if params[:commit] == 'Update'
      # Parse information required for update
      team ||= Team.find(params[:team_id].to_i)
      ticket ||= Ticket.find(params[:ticket].to_i)
      round ||= Round.find(params[:round].to_i)

      # Do not update pick if drop down list selection hasn't changed
      unless ticket.picks.where(round_id: round.id).blank? || team.nil?
        if ticket.picks.where(round_id: round.id).first.team_id != team.id
          pick = Pick.find(ticket.picks.where(round_id: round.id).first.id)
          pick.team_id = team.id
          if pick.save
            # Notify user
            #UserNotifier.picked(@user, pick).deliver
            respond_to do |format|
              format.html {redirect_to manage_user_path(@user),
                                       flash: {notice: "Updated pick to #{team.name} for user #{@user.username} successfully",
                                               success: true}}
            end
          else
            respond_to do |format|
              format.html {redirect_to manage_user_path(@user),
                                       flash: {notice: "Could not update pick for user #{@user.username}",
                                               success: false}}
            end
          end
        else
          respond_to do |format|
            format.html {redirect_to manage_user_path(@user),
                                     flash: {notice: "Nothing to update for this ticket",
                                             success: true}}
          end
        end
      end
    elsif params[:commit] == 'Remove'
      # Parse information required for update
      team ||= Team.find(params[:team_id].to_i)
      ticket ||= Ticket.find(params[:ticket].to_i)
      round ||= Round.find(params[:round].to_i)

      # Do not remove empty picks
      unless ticket.picks.where(round_id: round.id).blank? || team.nil?
        if ticket.picks.where(round_id: round.id).first.team_id == team.id
          pick = Pick.find(ticket.picks.where(round_id: round.id).first.id)
          if pick.destroy
            respond_to do |format|
              format.html {redirect_to manage_user_path(@user),
                                       flash: {notice: "Removed pick (#{team.name}) for user #{@user.username} successfully",
                                               success: true}}
            end
          else
            respond_to do |format|
              format.html {redirect_to manage_user_path(@user),
                                       flash: {notice: "Could not remove pick for user #{@user.username}",
                                               success: false}}
            end
          end
        else
          respond_to do |format|
            format.html {redirect_to manage_user_path(@user),
                                     flash: {notice: "Could not remove pick for user #{@user.username}: ID mismatch",
                                             success: false}}

          end
        end
      end
    end

  end

  def balances
    @users = User.all
  end

  def update_user_balance

    # Get user from table and credit/debit its balance from amount field value
    @user ||= User.find_by(id: params[:user_id].to_i)
    unless @user.nil?
      @user.balance += params[:amount].to_i
      @user.last_deposit = params[:amount].to_i
    end


    respond_to do |format|
      if @user.save
        #UserNotifier.deposit(@user).deliver
        format.html {redirect_to users_balances_path,
                                 flash: {notice: "User balance updated successfully for #{@user.username}",
                                        success: true}}
        format.json
      else
        format.html {redirect_to users_balances_path,
                                 flash: {notice: "Could not update balance for #{@user.username}",
                                         success: false}}
      end

    end

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.balance = 0

    respond_to do |format|
      if @user.save

        # Notify user
        #UserNotifier.registered(@user).deliver

        # Admin added user from backend
        if session[:user_id]
          format.html { redirect_to @user, flash: {notice: 'User was successfully added',
                                                   success: true} }
          format.json { render action: 'show', status: :created, location: @user }
        else
          session[:user_id] = @user.id
          format.html { redirect_to visitor_register_confirmation_path}
          format.json { render action: 'show', status: :created, location: @user }
        end

      # User registered himself from front-end
      else
        if session[:user_id]
          format.html { render action: 'new', flash: {notice: 'Could not add user',
                                                      success: false} }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        else
          session[:user_id] = nil
          format.html { render 'visitor/register',
                               layout: 'frontend',
                               flash: {notice: 'There was a problem creating your account, please retry',
                                                           success: false} }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end

      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    @user.update(user_params)

    respond_to do |format|
      if @user.save

        # Notify user
        #UserNotifier.registered(@user).deliver

        # Admin added user from backend
        if session[:admin_logged]
          format.html { redirect_to @user, flash: {notice: 'User was successfully updated',
                                                   success: true} }
          format.json { render action: 'show', status: :created, location: @user }

        # User registered himself from front-end
        else
          session[:user_id] = @user.id
          format.html { redirect_to visitor_update_confirmation_path}
          format.json { render action: 'show', status: :created, location: @user }
        end


      else
        if session[:admin_logged]
          format.html { render action: 'new', flash: {notice: 'Could not add user',
                                                      success: false} }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        else
          session[:user_id] = @user.id
          format.html { render 'visitor/register',
                               layout: 'frontend',
                               flash: {notice: 'There was a problem updating your account, please retry',
                                       success: false} }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end

      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :first_name, :last_name, :email, :phone, :country, :province, :dob)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def past_picks(ticket)

    # Past picks
    past_picks = []
    if ticket
      unless ticket.picks.count == 0
        ticket.picks.order(:created_at).each do |past_pick|
          unless past_pick.round == ticket.round
            past_picks << past_pick.team_id
          end
        end
      end

    end

    return past_picks

  end

  def possible_picks(round, ticket)
      # Past picks
      past_picks = past_picks(ticket)

      possible_picks = []

      # Completed round pick
      if ticket.validity
        if round.games.present?

          # For every game in round
          round.games.each do |game|

            # Make sure first team association id is not present in the possible_picks array
            # Also make sure doesn't select the same team twice for a survival ticket
            unless possible_picks.include?(game.first_team_id) || past_picks.include?(game.first_team_id)
              possible_picks << Team.find(game.first_team_id)
            end

            # Then, add the second team if it doesn't exist neither for the case of dual-game based rounds
            if round.with_games
              unless possible_picks.include?(game.second_team_id)|| past_picks.include?(game.second_team_id)
                possible_picks << Team.find(game.second_team_id)
              end
            end
          end

        end
      else
        possible_picks = nil
      end
      return possible_picks
  end

end

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
   <div class="alert alert-danger alert-dismissable"
        style="width: 62%; margin-bottom: 5%; margin-top: 5%; margin-left: auto; margin-right: auto;">
      <h4 style="color: darkred"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div style="width: 50%; margin: 0 auto;">
      <div class="field">
        <%= f.label :username %><br>
        <%= f.text_field :username, hide_label: true %>
      </div>
      <% unless session[:admin_logged] %>
          <div class="field">
            <%= f.label :password %><br>
            <%= f.password_field :password,  hide_label: true %>
          </div>
          <div class="field">
            <%= f.label :password_confirmation %><br>
            <%= f.password_field :password_confirmation,  hide_label: true %>
          </div>
      <% end %>
      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, hide_label: true %>
      </div>
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, hide_label: true %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, hide_label: true %>
      </div>
      <div class="field">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, hide_label: true %>
      </div>
      <div class="field">
        <%= f.label :country %><br>
        <%= f.select :country, I18nData.countries.values, selected: I18nData.countries['CA'], hide_label: true %>
      </div>
      <div class="field">
        <%= f.label :province %><br>
        <%= f.text_field :province, hide_label: true %>
      </div>
      <div class="field">
        <span style="font-weight: bold;">Date of Birth</span><br>
        <%= f.date_select :dob, hide_label: true,
                          start_year: Date.today.year - 18,
                          end_year: Date.today.year - 130,
                          default: Date.new(1990, 1, 1) %>
      </div>
      <% if session[:user_id] %>
          <div class="actions">
            <%= f.submit 'Update', class:"btn btn-success" %>
          </div>
      <% else %>
          <div class="actions">
            <%= f.submit 'Register', class:"btn btn-danger" %>
          </div>
      <% end %>
    </div>



<% end %>

app/views/users/balances.html.erb
<h1>Manage User Balances</h1>

<table class= "table table-striped" style="width: 100%; margin: 0 auto;">
  <thead>
      <tr>
        <th>User</th>
        <th>Full Name</th>
        <th>Amount(+/-)</th>
        <th>Balance</th>
        <th>Action</th>
      </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <%= form_tag users_balances_path, method: :put   do %>
          <%= hidden_field_tag :user_id, user.id%>
          <tr>
            <td>
              <%= user.username %>
            </td>
            <td>
              <%= user.first_name %> <%= user.last_name %>
            </td>
            <td>
              <%= number_field_tag :amount %>
            </td>
            <td>
              $<%= user.balance %>
            </td>
            <td>

              <%= submit_tag 'Credit/Debit', class: "btn btn-success" %>

            </td>
          </tr>
      <% end %>
  <% end %>
  </tbody>

</table>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Registered Users</h1>

<table class="table table-striped" style="width: 100%; margin: 0 auto;">
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Country</th>
      <th>Province</th>
      <th>Date of Birth</th>
      <th>Balance</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.country %></td>
        <td><%= user.province %></td>
        <td><%= user.dob %></td>
        <td>$<%= user.balance %></td>
        <td style="text-align: right" data-no-turbolink="true">
          <%= link_to 'Manage', manage_user_path(user)%>
          <span class="glyphicon glyphicon-dashboard pool-action-manage"></span>
          <br>
          <%= link_to 'Edit', edit_user_path(user)%>
          <span class="glyphicon glyphicon-pencil pool-action-edit"></span>
          <br>
          <%= link_to 'Remove',
                      user_path(user),
                      method: :delete,
                      data:{confirm: "Are you sure you want to remove user #{user.username}?
                      User has #{user.tickets.where(validity: true).count} alive tickets in FLP"}%>
          <span class="glyphicon glyphicon-trash pool-action-edit"></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<span style="float: right; padding-bottom: 2em; ">
  <%= button_to 'Add New User',
                new_user_path,
                class:"btn btn-warning",
                type:"button",
                method: :get%>
</span>

app/views/users/manage.html.erb
<h1>Manage <%= @user.first_name %> <%= @user.last_name%> </h1>
<h4 style="text-align: center">(<%= @user.username %>)</h4>

<% if @user.tickets.blank? %>
    <h4 style="text-align: center; margin-top: 2em;">No tickets to display for this user</h4>
<% else %>
    <% @user.pools.order(:league_id, :start_date).each do |pool| %>

        <% if pool.start_date > Date.today %>
            <h3 style="text-align: center; color: darkred; margin-bottom: 10%;">Upcoming Pool: <%= pool.name %></h3>
        <% elsif pool.end_date < Date.today %>
            <h3 style="text-align: center; color: green; margin-bottom: 10%;">Active Pool: <%= pool.name %></h3>
        <% elsif Date.today.between?(pool.start_date, pool.end_date) %>
            <h3 style="text-align: center; color: grey; margin-bottom: 10%;">Past Pool: <%= pool.name %></h3>
        <% end %>

        <% if pool.rounds.blank? %>
            <div class="alert alert-info" style="margin: 0 auto;">
              <td colspan="2">The pool associated with this ticket has no rounds yet</td>
            </div>
        <% else %>

        <% pool.rounds.order(:start_date, :with_games).each do |round| %>
            <h4 data-no-turbolink="true" style="margin-bottom: 5%"><%= link_to "Round #{round.name}", round_path(round) %></h4>
                <table class="table table-striped" style="margin-bottom: 10vh;">
                  <thead>
                  <% if round.complete %>
                    <tr>
                      <th colspan="4" style="color: lightcoral">This round is closed</th>
                    </tr>
                  <% end %>
                  <tr>
                    <th style="width: 20%;">
                      Ticket Action
                    </th>
                    <th style="width: 20%;">
                      Ticket
                    </th>
                    <th style="width: 20%">
                      Picks
                    </th>
                    <th style="width: 20%">
                      Pick Action
                    </th>
                  </tr>
                  </thead>

                  <tbody>
                  <% @user.tickets.where(pool: pool).each  do |ticket| %>
                      <tr>
                        <% if ticket.validity %>
                            <td><%= button_to 'Disable',
                                              { controller: :tickets, action: :disable, id: ticket.id },
                                              method: :put,
                                              class: "btn btn-danger",
                                              data: {confirm: "Are you sure you want to disable this ticket for #{@user.username}?"} %></td>
                            <td>
                        <% else %>
                            <td><%= button_to 'Enable',
                                              { controller: :tickets, action: :disable, id: ticket.id },
                                              method: :put,
                                              class: "btn btn-success",
                                              data: {confirm: "Are you sure you want to re-enable this ticket for #{@user.username}?"} %></td>
                            <td>
                        <% end %>

                          #<%= @user.tickets.where(pool: pool).index(ticket) + 1 %>
                        </td>
                        <% if ticket.picks.where(round_id: round.id).blank? %>
                            <%= bootstrap_form_tag url: 'add_managed_pick', method: :post do |p|%>
                                    <td>
                                      <%= p.collection_select :team_id,
                                                              possible_picks(round, ticket).to_a,
                                                              :id,
                                                              :name,
                                                              {hide_label: true,
                                                               include_blank: ticket.validity ? "No Picks" : "Invalid/Expired Ticket"},
                                                              disabled: !ticket.validity || round.complete%>
                                    </td>

                                    <td>
                                      <%= hidden_field_tag :ticket, ticket.id %>
                                      <%= hidden_field_tag :round, round.id %>
                                      <%= p.submit 'Add Pick',
                                                   class: "btn btn-success",
                                                   disabled: !ticket.validity || round.complete,
                                                   data: {confirm: "Are you sure you want to add this pick to user ticket?"} %>
                                    </td>


                            <% end %>
                        <% else %>
                            <%= bootstrap_form_tag url: 'update_managed_pick', method: :put do |p|%>
                                <td>
                                  <%= p.collection_select :team_id,
                                                          possible_picks(round, ticket).to_a.concat([Team.find(ticket.picks.where(round_id: round.id).first.team_id)]),
                                                          :id,
                                                          :name,
                                                          {hide_label: true,
                                                           selected: ticket.picks.where(round_id: round.id).first.team_id,
                                                           include_blank: ticket.validity ? false : "Invalid/Expired Ticket" },
                                                          disabled: !ticket.validity || round.complete%>

                                </td>
                                <td>
                                  <%= hidden_field_tag :ticket, ticket.id %>
                                  <%= hidden_field_tag :round, round.id %>
                                  <%= p.submit 'Update',
                                               class: "btn btn-primary",
                                               disabled: !ticket.validity || round.complete,
                                               data: {confirm: "Are you sure you want to change this pick for this ticket?"} %>
                                  <%= hidden_field_tag :ticket, ticket.id %>
                                  <%= hidden_field_tag :round, round.id %>
                                  <%= p.submit 'Remove',
                                               class: "btn btn-danger",
                                               disabled: !ticket.validity || round.complete,
                                               data: {confirm: "Are you sure you want to remove this pick from  user ticket?"}  %>
                                </td>
                            <% end %>
                        <% end %>


                      </tr>
                  <% end %>
                  </tbody>
                </table>
            <% end %>

        <% end %>

    <% end %>

<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>

<p>
  <strong>Province:</strong>
  <%= @user.province %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>